// AUTO-GENERATED - Do not edit manually
// Generated by /api/dev/publish
// This file maps component slugs to their file paths for dynamic imports

export interface RegistryEntry {
  path: string;
  hasComplexDeps: boolean;
  displayName: string;
}

export const COMPONENT_REGISTRY: Record<string, RegistryEntry> = {
  'border-beam': { path: '@/components/ui/BorderBeam', hasComplexDeps: false, displayName: 'BorderBeam' },
  'flow-threads': { path: '@/components/ui/FlowThreads', hasComplexDeps: true, displayName: 'FlowThreads' },
  'hover-border-trail': { path: '@/components/ui/HoverBorderTrail', hasComplexDeps: false, displayName: 'HoverBorderTrail' },
  'liquid-ether': { path: '@/components/ui/LiquidEther', hasComplexDeps: true, displayName: 'LiquidEther' },
  'magnet-card': { path: '@/components/ui/MagnetCard', hasComplexDeps: false, displayName: 'MagnetCard' },
  'noise-trail': { path: '@/components/ui/NoiseTrail', hasComplexDeps: false, displayName: 'NoiseTrail' },
  'pulse-button': { path: '@/components/ui/PulseButton', hasComplexDeps: false, displayName: 'PulseButton' },
  'ripple-button': { path: '@/components/ui/RippleButton', hasComplexDeps: false, displayName: 'RippleButton' },
  'shimmer-button': { path: '@/components/ui/ShimmerButton', hasComplexDeps: false, displayName: 'ShimmerButton' },
  'spark-cursor': { path: '@/components/ui/SparkCursor', hasComplexDeps: false, displayName: 'SparkCursor' },
  'stateful-button': { path: '@/components/ui/StatefulButton', hasComplexDeps: false, displayName: 'StatefulButton' }
};

// Complex dependency packages that require file-based imports
// Components with these dependencies cannot be dynamically rendered from DB code
export const COMPLEX_DEP_PACKAGES = [
  'three',
  'gsap',
  '@react-three/fiber',
  '@react-three/drei',
  'lottie-react',
  'matter-js',
  'pixi.js',
  'babylon',
  'd3',
  'canvas',
  'ogl',
];
